import React,{useEffect,useState} from 'react';
import './admin.css';
const api=async(path,opts={})=>{const r=await fetch(path,{credentials:'same-origin',...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});const d=r.status===204?{}:await r.json();if(!r.ok)throw new Error(d.error||'Erreur');return d;};
export default function Admin(){const [logged,setLogged]=useState(false),[loginEmail,setLoginEmail]=useState(''),[password,setPassword]=useState(''),[csrf,setCsrf]=useState(''),[data,setData]=useState(null),[audit,setAudit]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[form,setForm]=useState({name:'',version:'',status:'pending',notes:''}),[account,setAccount]=useState({email:'',password:'',role:'ADMIN'});
const load=async()=>{try{const d=await api('/api/admin/overview');const a=await api('/api/admin/audit');setData(d);setAudit(a.events||[]);setLogged(true)}catch(e){if(e.message!=='ADMIN_AUTH_REQUIRED')setError(e.message)}finally{setLoading(false)}};
useEffect(()=>{load()},[]);
const login=async e=>{e.preventDefault();setError('');try{const d=await api('/api/admin/login',{method:'POST',body:JSON.stringify({email:loginEmail,password})});setCsrf(d.csrf);setPassword('');await load()}catch(e){setError(e.message)}};
const act=async(path,method='POST',body)=>{setError('');try{await api(path,{method,body:body?JSON.stringify(body):undefined,headers:{'x-csrf-token':csrf}});await load()}catch(e){setError(e.message)}};
const createAccount=async()=>{setError('');try{await act('/api/admin/accounts','POST',account);setAccount({email:'',password:'',role:'ADMIN'})}catch(e){setError(e.message)}};
if(loading)return <div className="admin-shell"><div className="admin-loading">NOVUS ADMIN · SECURE BOOT…</div></div>;
if(!logged)return <div className="admin-shell"><div className="login-card"><div className="brand"><span className="brand-mark">N</span> NOVUS ADMIN</div><p>Console d'administration protégée. Aucun secret n'est stocké dans le navigateur.</p><form onSubmit={login}><input autoFocus type="email" placeholder="Email administrateur" value={loginEmail} onChange={e=>setLoginEmail(e.target.value)}/><input type="password" placeholder="Mot de passe administrateur" value={password} onChange={e=>setPassword(e.target.value)}/><button className="button primary">Authentifier →</button></form>{error&&<div className="admin-error">⚠ {error}</div>}</div></div>;
const plugins=data?.plugins||[],stats={total:plugins.length,approved:plugins.filter(x=>x.status==='approved').length,pending:plugins.filter(x=>x.status==='pending').length,rejected:plugins.filter(x=>x.status==='rejected').length};
return <div className="admin-shell"><header className="admin-nav"><a className="brand" href="/"><span className="brand-mark">N</span> NOVUS <span className="admin-badge">ADMIN</span></a><div className="admin-health"><i/> SECURE CONTROL PLANE</div><button className="button ghost" onClick={()=>act('/api/admin/logout')}>Déconnexion</button></header><main className="admin-main"><div className="admin-heading"><div><span>CONTROL CENTER / GOVERNANCE</span><h1>Administration <em>NOVUS.</em></h1><p>Gestion locale des plugins, comptes, quarantaine, décisions et journal d'audit.</p></div><div className="security-score"><strong>HARDENED</strong><small>AUTH · CSRF · RATE LIMIT · AUDIT</small></div></div>{error&&<div className="admin-error">⚠ {error}</div>}
<section className="metric-grid">{[['Plugins',stats.total],['Validés',stats.approved],['En revue',stats.pending],['Rejetés',stats.rejected],['Quarantaine',data?.quarantineCount||0],['Comptes',data?.accounts?.length||0]].map(([k,v])=><div className="metric" key={k}><span>{k}</span><strong>{v}</strong></div>)}</section>
<section className="admin-grid"><div className="admin-panel"><div className="panel-title"><span>PLUGIN REGISTRY</span><b>LOCAL · NO GITHUB WRITE</b></div><div className="plugin-form"><input placeholder="Nom du plugin" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Version" value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="pending">En revue</option><option value="approved">Validé</option><option value="maintenance">Maintenance</option><option value="rejected">Rejeté</option></select><input placeholder="Note interne" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button className="button primary" onClick={async()=>{await act('/api/admin/plugins','POST',form);setForm({name:'',version:'',status:'pending',notes:''})}}>+ Ajouter</button></div><div className="plugin-list">{plugins.length===0&&<div className="empty">Aucun plugin enregistré. Ajoute le premier ci-dessus.</div>}{plugins.map(p=><div className="plugin-row" key={p.id}><div><strong>{p.name}</strong><small>{p.version||'version non définie'} · {new Date(p.updatedAt).toLocaleString('fr-FR')}</small>{p.notes&&<p>{p.notes}</p>}</div><select value={p.status} onChange={e=>act(`/api/admin/plugins/${p.id}`,'PATCH',{status:e.target.value})}><option value="pending">REVIEW</option><option value="approved">APPROVED</option><option value="maintenance">MAINTENANCE</option><option value="rejected">REJECTED</option></select><button className="danger" onClick={()=>act(`/api/admin/plugins/${p.id}`,'DELETE')}>×</button></div>)}</div></div>
<aside className="admin-panel"><div className="panel-title"><span>QUICK ACCOUNT</span><b>{data?.quickCreateEnabled?'ENABLED':'DISABLED'}</b></div><p className="muted">Création rapide d'un compte directement depuis le panneau. Le mot de passe est hashé avec scrypt et n'est jamais écrit dans GitHub.</p><div className="plugin-form"><input type="email" placeholder="Email" value={account.email} onChange={e=>setAccount({...account,email:e.target.value})}/><input type="password" placeholder="Mot de passe (12 caractères min.)" value={account.password} onChange={e=>setAccount({...account,password:e.target.value})}/><select value={account.role} onChange={e=>setAccount({...account,role:e.target.value})}><option value="ADMIN">ADMIN</option><option value="MODERATOR">MODERATOR</option><option value="OWNER">OWNER</option></select><button className="button primary" disabled={!data?.quickCreateEnabled} onClick={createAccount}>+ Créer le compte</button><a className="button ghost" href="/admin/quick-create">Ouvrir la page dédiée →</a><button className="button ghost" onClick={()=>act('/api/admin/quick-create/toggle','POST',{enabled:!data?.quickCreateEnabled})}>{data?.quickCreateEnabled?'Désactiver la création rapide':'Réactiver la création rapide'}</button></div><div className="plugin-list">{(data?.accounts||[]).map(u=><div className="plugin-row" key={u.id}><div><strong>{u.email}</strong><small>{u.role} · {new Date(u.createdAt).toLocaleString('fr-FR')}</small></div><b>{u.enabled?'ACTIVE':'DISABLED'}</b></div>)}</div></aside></section>
<section className="admin-grid"><aside className="admin-panel"><div className="panel-title"><span>SECURITY POSTURE</span><b>LIVE</b></div><div className="security-list"><div>🔐 Admin session <strong>8h · HttpOnly</strong></div><div>🛡️ CSRF protection <strong>ACTIVE</strong></div><div>⏱️ Login rate limit <strong>8 / 10 min</strong></div><div>📦 Upload rate limit <strong>12 / hour</strong></div><div>🧾 Audit trail <strong>LOCAL</strong></div><div>🔒 Quarantine files <strong>0600</strong></div><div>🐙 GitHub automation <strong>{data?.githubConfigured?'CONFIGURED':'DISABLED'}</strong></div><div>💬 Discord webhook <strong>{data?.discordConfigured?'CONFIGURED':'DISABLED'}</strong></div></div></aside><div className="admin-panel"><div className="panel-title"><span>QUARANTINE</span><b>{data?.quarantineCount||0} FILE(S)</b></div><div className="quarantine-list">{(data?.quarantine||[]).map(x=><div key={x.name}><span>🔒 {x.name}</span><small>{(x.size/1024/1024).toFixed(2)} MB</small></div>)}{!data?.quarantine?.length&&<div className="empty">Quarantaine vide.</div>}</div><button className="button danger-wide" onClick={()=>act('/api/admin/quarantine/purge')}>Vider la quarantaine</button></div></section>
<section className="admin-grid"><div className="admin-panel"><div className="panel-title"><span>AUDIT TRAIL</span><b>LAST 200</b></div><div className="audit-list">{audit.slice(0,14).map((x,i)=><div key={i}><time>{new Date(x.at).toLocaleTimeString('fr-FR')}</time><span>{x.action}</span><small>{x.name||x.email||x.id||''}</small></div>)}</div></div></section><div className="admin-footer"><span>Repository communautaire : <strong>{data?.githubRepo}</strong></span><span>Production changes require explicit admin action.</span></div></main></div>}
