import React,{useCallback,useEffect,useMemo,useState} from 'react';
import './admin.css';

const api=async(path,opts={})=>{const headers={'Content-Type':'application/json',...(opts.headers||{})};const token=sessionStorage.getItem('novus_admin_csrf');if(token&&!headers['x-csrf-token'])headers['x-csrf-token']=token;const r=await fetch(path,{credentials:'same-origin',...opts,headers});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={error:text||'Réponse invalide'}}if(!r.ok)throw Object.assign(new Error(data.error||`Erreur HTTP ${r.status}`),{status:r.status,data});return data};
const fmtBytes=n=>{if(!n)return'0 B';const u=['B','KB','MB','GB'];let i=0,x=n;while(x>=1024&&i<u.length-1){x/=1024;i++}return`${x.toFixed(i?1:0)} ${u[i]}`};
const fmtUptime=s=>{s=Math.max(0,Math.floor(s||0));const d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);return`${d?d+'j ':''}${h}h ${m}m`};

export default function Admin(){
 const[logged,setLogged]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[csrf,setCsrf]=useState(()=>sessionStorage.getItem('novus_admin_csrf')||''),[me,setMe]=useState(null),[data,setData]=useState(null),[audit,setAudit]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[tab,setTab]=useState('dashboard'),[search,setSearch]=useState(''),[account,setAccount]=useState({email:'',password:'',role:'USER',displayName:''}),[form,setForm]=useState({name:'',version:'',description:''}),[update,setUpdate]=useState(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const d=await api('/api/admin/overview');const a=await api('/api/admin/audit');setData(d);setAudit(a.events||[]);setLogged(true);if(d.admin){setMe(d.admin);setEmail(d.admin.email)}}catch(e){if(e.status===401){setLogged(false)}else setError(e.message)}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const login=async e=>{e.preventDefault();setError('');setBusy(true);try{const d=await api('/api/admin/login',{method:'POST',body:JSON.stringify({email,password})});sessionStorage.setItem('novus_admin_csrf',d.csrf);setCsrf(d.csrf);setMe({email:d.email,role:d.role});setPassword('');await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const act=async(path,method='POST',body)=>{setError('');setBusy(true);try{await api(path,{method,body:body===undefined?undefined:JSON.stringify(body)});await load();return true}catch(e){setError(e.message);if(e.status===401){sessionStorage.removeItem('novus_admin_csrf');setCsrf('');setLogged(false)}return false}finally{setBusy(false)}};
 const logout=async()=>{try{await api('/api/admin/logout',{method:'POST'})}catch{}sessionStorage.removeItem('novus_admin_csrf');setCsrf('');setLogged(false);setMe(null)};
 const stats=useMemo(()=>{const p=data?.plugins||[];return{total:p.length,approved:p.filter(x=>x.status==='approved'&&!x.archived).length,pending:p.filter(x=>x.status==='pending').length,archived:p.filter(x=>x.archived).length,accounts:data?.accounts?.length||0,quarantine:data?.quarantineCount||0}},[data]);
 const filtered=(data?.plugins||[]).filter(p=>`${p.name} ${p.author} ${p.status} ${p.version}`.toLowerCase().includes(search.toLowerCase()));
 const revisionAction=(r,action)=>act(`/api/admin/plugins/${r.pluginId}/revisions/${r.id}`,'POST',{action});
 if(loading)return <div className="admin-shell"><div className="admin-loading">NOVUS ADMIN · SECURE BOOT…</div></div>;
 if(!logged)return <div className="admin-shell"><div className="login-card"><div className="brand"><span className="brand-mark">N</span> NOVUS ADMIN</div><p>Console d'administration protégée. Session HttpOnly, contrôle CSRF, rate-limit et audit actifs.</p><form onSubmit={login}><input required autoComplete="username" type="email" placeholder="Email administrateur" value={email} onChange={e=>setEmail(e.target.value)}/><input required autoComplete="current-password" type="password" placeholder="Mot de passe" value={password} onChange={e=>setPassword(e.target.value)}/><button disabled={busy} className="button primary">{busy?'Authentification…':'Authentifier →'}</button></form>{error&&<div className="admin-error">⚠ {error}</div>}</div></div>;
 return <div className="admin-shell">
  <header className="admin-nav"><a className="brand" href="/"><span className="brand-mark">N</span> NOVUS <span className="admin-badge">{me?.role||'CONTROL'}</span></a><div className="admin-health"><i/> CONTROL PLANE · LIVE</div><div className="admin-user">{me?.email||email}</div><button className="button ghost" onClick={logout}>Déconnexion</button></header>
  <main className="admin-main"><div className="admin-heading"><div><span>CONTROL CENTER / GOVERNANCE</span><h1>Administration <em>NOVUS.</em></h1><p>Une seule console pour les comptes, plugins, révisions, sécurité, quarantaine, GitHub et mises à jour.</p></div><div className="security-score"><strong>HARDENED</strong><small>SESSION · CSRF · RATE LIMIT · AUDIT</small></div></div>{error&&<div className="admin-error">⚠ {error}<button onClick={()=>setError('')}>×</button></div>}
  <div className="admin-tabs">{[['dashboard','📊 Dashboard'],['plugins','🔌 Plugins'],['revisions','🧪 Révisions'],['accounts','👥 Comptes'],['security','🔐 Sécurité'],['audit','🧾 Audit'],['system','⚙️ Système']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==='dashboard'&&<><section className="metric-grid">{[['Plugins',stats.total],['Validés',stats.approved],['En revue',stats.pending],['Archivés',stats.archived],['Quarantaine',stats.quarantine],['Comptes',stats.accounts]].map(([k,v])=><div className="metric" key={k}><span>{k}</span><strong>{v}</strong></div>)}</section><section className="admin-grid"><div className="admin-panel"><div className="panel-title"><span>SERVER TELEMETRY</span><b>LIVE</b></div><div className="security-list"><div>⏱️ Uptime <strong>{fmtUptime(data?.stats?.uptime)}</strong></div><div>🧠 RAM process <strong>{fmtBytes(data?.stats?.memory?.rss)}</strong></div><div>💾 Heap <strong>{fmtBytes(data?.stats?.memory?.heapUsed)} / {fmtBytes(data?.stats?.memory?.heapTotal)}</strong></div><div>🖥️ CPU <strong>{data?.stats?.cpu?.cores} cores · load {(data?.stats?.cpu?.load?.[0]??0).toFixed(2)}</strong></div><div>🟢 Node <strong>{data?.stats?.node}</strong></div><div>🌐 Environment <strong>{data?.stats?.env}</strong></div></div></div><div className="admin-panel"><div className="panel-title"><span>INTEGRATIONS</span><b>STATUS</b></div><div className="security-list"><div>🐙 GitHub <strong>{data?.githubConfigured?'CONNECTED':'NOT CONFIGURED'}</strong></div><div>💬 Discord <strong>{data?.discordConfigured?'CONNECTED':'NOT CONFIGURED'}</strong></div><div>🔄 Auto-update <strong>{data?.autoUpdate?'ENABLED':'DISABLED'}</strong></div><div>🌿 Branch <strong>{data?.updateBranch}</strong></div><div>🧪 Pending reviews <strong>{data?.pendingRevisions?.length||0}</strong></div></div><button disabled={busy} className="button primary" onClick={async()=>{try{setUpdate(await api('/api/admin/update/check',{method:'POST'}))}catch(e){setError(e.message)}}}>Vérifier GitHub</button>{update&&<div className="empty">{update.upToDate?'✓ Production à jour':'⚠ Une mise à jour est disponible'}<br/><small>{update.local?.slice(0,8)} → {update.remote?.slice(0,8)}</small></div>}</div></section></>}
  {tab==='plugins'&&<section className="admin-panel"><div className="panel-title"><span>PLUGIN REGISTRY</span><b>{filtered.length} PLUGINS</b></div><div className="plugin-form"><input placeholder="Nom du plugin" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Version" value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/><input placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button disabled={busy} className="button primary" onClick={async()=>{if(await act('/api/admin/plugins','POST',form))setForm({name:'',version:'',description:''})}}>+ Ajouter</button></div><input className="admin-search" placeholder="Rechercher un plugin, auteur, version…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="plugin-list">{filtered.map(p=><div className="plugin-row" key={p.id}><div><strong>{p.name}</strong><small>v{p.version||'—'} · {p.author} · {p.revisionCount} révisions</small><p>{p.description}</p></div><select value={p.status} onChange={e=>act(`/api/admin/plugins/${p.id}`,'PATCH',{status:e.target.value})}><option value="pending">REVIEW</option><option value="approved">APPROVED</option><option value="maintenance">MAINTENANCE</option><option value="rejected">REJECTED</option></select><button className="button ghost" onClick={()=>act(`/api/admin/plugins/${p.id}`,'PATCH',{archived:!p.archived})}>{p.archived?'Désarchiver':'Archiver'}</button><button className="danger" onClick={()=>{if(confirm(`Supprimer ${p.name} ?`))act(`/api/admin/plugins/${p.id}`,'DELETE')}}>×</button></div>)}{!filtered.length&&<div className="empty">Aucun plugin.</div>}</div></section>}
  {tab==='revisions'&&<section className="admin-panel"><div className="panel-title"><span>COMMUNITY REVIEW QUEUE</span><b>{data?.pendingRevisions?.length||0} PENDING</b></div><p className="muted">Chaque création ou modification communautaire passe par cette file. Une approbation applique la révision et publie le plugin.</p><div className="plugin-list">{(data?.pendingRevisions||[]).map(r=><div className="plugin-row" key={r.id}><div><strong>{r.pluginName}</strong><small>{r.type==='edit'?'Modification':'Création'} · v{r.version||'—'} · {new Date(r.createdAt).toLocaleString('fr-FR')}</small><p>{r.changes?.description||r.description||'Nouvelle proposition'}</p></div><button className="button primary" onClick={()=>revisionAction(r,'approve')}>✓ Valider</button><button className="button ghost" onClick={()=>revisionAction(r,'reject')}>Rejeter</button></div>)}{!data?.pendingRevisions?.length&&<div className="empty">Aucune révision en attente.</div>}</div></section>}
  {tab==='accounts'&&<section className="admin-grid"><div className="admin-panel"><div className="panel-title"><span>ACCOUNT MANAGEMENT</span><b>{data?.accounts?.length||0}</b></div><div className="plugin-form"><input placeholder="Nom / pseudo" value={account.displayName} onChange={e=>setAccount({...account,displayName:e.target.value})}/><input type="email" placeholder="Email" value={account.email} onChange={e=>setAccount({...account,email:e.target.value})}/><input type="password" placeholder="Mot de passe · 12 min" value={account.password} onChange={e=>setAccount({...account,password:e.target.value})}/><select value={account.role} onChange={e=>setAccount({...account,role:e.target.value})}><option>USER</option><option>MODERATOR</option><option>ADMIN</option><option>OWNER</option></select><button disabled={busy} className="button primary" onClick={async()=>{if(await act('/api/admin/accounts','POST',account))setAccount({email:'',password:'',role:'USER',displayName:''})}}>Créer</button></div></div><div className="admin-panel"><div className="panel-title"><span>MEMBERS</span><b>ACTIVE / DISABLED</b></div><div className="plugin-list">{(data?.accounts||[]).map(u=><div className="plugin-row" key={u.id}><div><strong>{u.displayName} · {u.email}</strong><small>{u.role} · {new Date(u.createdAt).toLocaleDateString('fr-FR')}</small></div><button className="button ghost" onClick={()=>act(`/api/admin/accounts/${u.id}`,'PATCH',{enabled:!u.enabled})}>{u.enabled?'Désactiver':'Activer'}</button><button className="danger" onClick={()=>{if(confirm(`Supprimer ${u.email} ?`))act(`/api/admin/accounts/${u.id}`,'DELETE')}}>×</button></div>)}</div></div></section>}
  {tab==='security'&&<section className="admin-grid"><div className="admin-panel"><div className="panel-title"><span>SECURITY POSTURE</span><b>LIVE</b></div><div className="security-list"><div>🔐 Admin sessions <strong>8h · HttpOnly · SameSite</strong></div><div>🛡️ CSRF <strong>ACTIVE</strong></div><div>⏱️ Admin login <strong>8 / 10 min / IP</strong></div><div>👤 Registration <strong>5 / hour / IP</strong></div><div>🔑 Passwords <strong>scrypt + random salt</strong></div><div>📦 Private data <strong>0600</strong></div><div>👑 Active OWNERs <strong>{(data?.accounts||[]).filter(x=>x.role==='OWNER'&&x.enabled).length}</strong></div></div></div><div className="admin-panel"><div className="panel-title"><span>QUICK ACCOUNT</span><b>{data?.quickCreateEnabled?'ENABLED':'DISABLED'}</b></div><p className="muted">Création d'urgence contrôlée par l'administration. Le compte communautaire normal reste disponible via /account et /plugins.</p><button className="button ghost" onClick={()=>act('/api/admin/quick-create/toggle','POST',{enabled:!data?.quickCreateEnabled})}>{data?.quickCreateEnabled?'Désactiver':'Réactiver'} Quick Account</button></div></section>}
  {tab==='audit'&&<section className="admin-panel"><div className="panel-title"><span>AUDIT TRAIL</span><b>LAST 500</b></div><div className="audit-list">{audit.map((x,i)=><div key={i}><time>{new Date(x.at).toLocaleString('fr-FR')}</time><span>{x.action}</span><small>{x.email||x.by||x.pluginId||x.id||''}</small></div>)}{!audit.length&&<div className="empty">Aucun événement.</div>}</div></section>}
  {tab==='system'&&<section className="admin-grid"><div className="admin-panel"><div className="panel-title"><span>QUARANTINE</span><b>{data?.quarantineCount||0} FILES</b></div><div className="quarantine-list">{(data?.quarantine||[]).map(x=><div key={x.name}><span>🔒 {x.name}</span><small>{fmtBytes(x.size)}</small></div>)}{!data?.quarantine?.length&&<div className="empty">Quarantaine vide.</div>}</div><button disabled={busy} className="button danger-wide" onClick={()=>{if(confirm('Vider toute la quarantaine ?'))act('/api/admin/quarantine/purge')}}>Vider la quarantaine</button></div><div className="admin-panel"><div className="panel-title"><span>UPDATES</span><b>{data?.autoUpdate?'AUTO':'MANUAL'}</b></div><p className="muted">Branche : {data?.updateBranch}. Le serveur vérifie et peut appliquer les mises à jour GitHub.</p><button className="button primary" onClick={async()=>{try{setUpdate(await api('/api/admin/update/check',{method:'POST'}))}catch(e){setError(e.message)}}}>Vérifier</button><button className="button ghost" onClick={()=>act('/api/admin/update/apply')}>Appliquer</button></div></section>}
  <footer className="admin-footer"><span>Repository : <strong>{data?.githubRepo}</strong></span><span>Community → review → validation → publication</span><span>Session : {csrf?'CSRF READY':'CSRF SESSION MISSING'}</span></footer>
 </main></div>;
}
