import React,{useEffect,useMemo,useRef,useState} from 'react';
import './community.css';
const api=async(path,opts={})=>{const r=await fetch(path,{credentials:'same-origin',...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});const text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch{d={error:text||'Erreur serveur'}}if(!r.ok)throw Error(d.error||`Erreur HTTP ${r.status}`);return d};
const formatBytes=n=>{if(!Number.isFinite(n))return '—';if(n<1024)return `${n} o`;if(n<1024**2)return `${(n/1024).toFixed(1)} Ko`;if(n<1024**3)return `${(n/1024**2).toFixed(1)} Mo`;return `${(n/1024**3).toFixed(1)} Go`};
const sha256=async file=>{const hash=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')};
const fileToBase64=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]||'');r.onerror=reject;r.readAsDataURL(file)});
const steps=['Informations','Fichier','Vérification','Récapitulatif'];
export default function Community(){
 const initialMode=location.pathname.startsWith('/account')?'account':'plugins';
 const[user,setUser]=useState(null),[plugins,setPlugins]=useState([]),[q,setQ]=useState(''),[mode,setMode]=useState(initialMode),[busy,setBusy]=useState(true),[error,setError]=useState(''),[auth,setAuth]=useState({email:'',password:'',displayName:''}),[form,setForm]=useState({name:'',version:'',description:'',author:'',category:'General',icon:''}),[selected,setSelected]=useState(null),[contrib,setContrib]=useState([]),[profile,setProfile]=useState({displayName:'',password:''}),[authMode,setAuthMode]=useState('login');
 const[step,setStep]=useState(0),[file,setFile]=useState(null),[fileHash,setFileHash]=useState(''),[fileBusy,setFileBusy]=useState(false),[checks,setChecks]=useState([]),[submitBusy,setSubmitBusy]=useState(false),[submitted,setSubmitted]=useState(false),[drag,setDrag]=useState(false),inputRef=useRef(null);
 const load=async()=>{try{const m=await api('/api/me');setUser(m.user||null);const p=await api('/api/plugins');setPlugins(p.plugins||[]);if(m.user){const c=await api('/api/my/contributions');setContrib(c.contributions||[]);setProfile({displayName:m.user.displayName,password:''})}else if(initialMode==='account')setMode('login')}catch(e){setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const search=async value=>{setQ(value);try{const d=await api('/api/plugins?q='+encodeURIComponent(value));setPlugins(d.plugins||[])}catch(e){setError(e.message)}};
 const authenticate=async()=>{setError('');try{const d=await api(authMode==='register'?'/api/auth/register':'/api/auth/login',{method:'POST',body:JSON.stringify(auth)});setUser(d.user);setMode('account');await load()}catch(e){setError(e.message)}};
 const resetWizard=()=>{setStep(0);setFile(null);setFileHash('');setChecks([]);setSubmitted(false);setSubmitBusy(false);setForm({name:'',version:'',description:'',author:user?.displayName||'',category:'General',icon:''})};
 const openWizard=()=>{if(!user){setAuthMode('login');setMode('login');return}resetWizard();setMode('contribute')};
 const acceptFile=async f=>{if(!f)return;setError('');const ext=f.name.toLowerCase().split('.').pop();if(!['jar','zip'].includes(ext)){setError('Format invalide. Seuls les fichiers .jar et .zip sont acceptés.');return}if(f.size>10*1024*1024){setError('Fichier trop volumineux. Limite : 10 Mo.');return}setFileBusy(true);try{const h=await sha256(f);setFile(f);setFileHash(h);setStep(1);setChecks([])}catch{setError('Impossible de calculer le SHA-256 du fichier.')}finally{setFileBusy(false)}};
 const runChecks=async()=>{if(!file)return;setStep(2);setChecks([]);const list=[['Format','Extension .jar/.zip valide'],['Taille','Fichier sous la limite de 10 Mo'],['Intégrité','SHA-256 calculé côté navigateur'],['Métadonnées','Nom, version et description renseignés'],['Sécurité','Le fichier sera conservé en quarantaine avant revue']];for(const [name,detail] of list){await new Promise(r=>setTimeout(r,380));setChecks(c=>[...c,{name,detail,ok:true}])}await new Promise(r=>setTimeout(r,450));setStep(3)};
 const submitPlugin=async()=>{if(!user||!file)return;setSubmitBusy(true);setError('');try{const data=await fileToBase64(file);await api('/api/contributions',{method:'POST',body:JSON.stringify({filename:file.name,data,author:user.displayName||user.email})});await api('/api/plugins',{method:'POST',body:JSON.stringify({name:form.name,version:form.version,description:`[${form.category}]${form.icon?` [logo:${form.icon}]`:''} ${form.description}`})});setSubmitted(true);setStep(4);await load()}catch(e){setError(e.message)}finally{setSubmitBusy(false)}};
 const editPlugin=async()=>{if(!selected||!user)return;try{const r=await api('/api/plugins/'+selected.id,{method:'PATCH',body:JSON.stringify({name:selected.name,version:selected.version,description:selected.description})});setSelected(null);setError(`Modification envoyée en revue · ${r.revisionId||'OK'}`);await load()}catch(e){setError(e.message)}};
 const saveProfile=async()=>{try{const d=await api('/api/me',{method:'PATCH',body:JSON.stringify(profile)});setUser(d.user);setProfile({...profile,password:''});setError('Profil enregistré ✓')}catch(e){setError(e.message)}};
 const logout=async()=>{try{await api('/api/auth/logout',{method:'POST'})}catch{}setUser(null);setContrib([]);setMode('plugins')};
 const canNext=useMemo(()=>step===0?Boolean(form.name&&form.version&&form.description):step===1?Boolean(file):step===2?checks.length===5:true,[step,form,file,checks]);
 if(busy)return <div className="community"><div className="community-loading">NOVUS COMMUNITY · CHARGEMENT…</div></div>;
 return <div className="community"><header className="community-nav"><a href="/" className="community-brand"><span>N</span>NOVUS</a><nav><button className={mode==='plugins'?'active':''} onClick={()=>setMode('plugins')}>Plugins</button><button className={mode==='contribute'?'active':''} onClick={openWizard}>Contribuer</button>{user&&<button className={mode==='contributions'?'active':''} onClick={()=>setMode('contributions')}>Mes contributions</button>}{user&&<button className={mode==='account'?'active':''} onClick={()=>setMode('account')}>Mon compte</button>}</nav><div className="community-user">{user?<><span>{user.displayName}</span>{['OWNER','ADMIN','MODERATOR'].includes(user.role)&&<a href="/admin">Admin</a>}<button onClick={logout}>Déconnexion</button></>:<button onClick={()=>{setAuthMode('login');setMode('login')}}>Se connecter</button>}</div></header>
 <main className="community-main">{error&&<div className="community-alert">{error}<button onClick={()=>setError('')}>×</button></div>}
 {mode==='login'&&!user&&<section className="community-card auth-card"><span className="eyebrow">COMPTE NOVUS</span><h1>{authMode==='register'?'Rejoindre NOVUS':'Bon retour.'}</h1><p>{authMode==='register'?'Ton compte te permet de proposer des plugins, suivre tes révisions et gérer ton profil.':'Connecte-toi pour retrouver tes contributions et continuer à contribuer.'}</p>{authMode==='register'&&<input placeholder="Pseudo" value={auth.displayName} onChange={e=>setAuth({...auth,displayName:e.target.value})}/>}<input placeholder="Email" type="email" autoComplete="email" value={auth.email} onChange={e=>setAuth({...auth,email:e.target.value})}/><input placeholder="Mot de passe · 12 caractères min." type="password" autoComplete={authMode==='register'?'new-password':'current-password'} value={auth.password} onChange={e=>setAuth({...auth,password:e.target.value})}/><div className="auth-actions"><button className="primary" disabled={!auth.email||!auth.password} onClick={authenticate}>{authMode==='register'?'Créer mon compte':'Me connecter'}</button><button onClick={()=>setAuthMode(authMode==='register'?'login':'register')}>{authMode==='register'?'J’ai déjà un compte':'Créer un compte'}</button></div></section>}
 {mode==='plugins'&&<><section className="community-hero"><div><span className="eyebrow">COMMUNITY PLUGIN HUB</span><h1>Les plugins de <em>la communauté.</em></h1><p>Explore, propose des améliorations et aide à faire évoluer NOVUS. Chaque modification communautaire repasse par une validation avant publication.</p></div><button className="primary" onClick={openWizard}>+ Proposer un plugin</button></section><div className="plugin-toolbar"><input value={q} onChange={e=>search(e.target.value)} placeholder="Rechercher un plugin…"/><span>{plugins.length} résultat{plugins.length>1?'s':''}</span></div><section className="plugin-grid">{plugins.map(p=><article className="community-plugin" key={p.id} onClick={()=>setSelected({...p})}><div className="plugin-status">{p.status==='approved'?'✓ VALIDÉ':p.status.toUpperCase()}</div><h2>{p.name}</h2><p>{p.description}</p><footer><span>v{p.version||'—'}</span><span>par {p.author}</span><span>{p.revisionCount} révision{p.revisionCount>1?'s':''}</span></footer></article>)}{!plugins.length&&<div className="empty-community">Aucun plugin ne correspond à ta recherche.</div>}</section></>}
 {mode==='contribute'&&user&&<section className="wizard-card"><div className="wizard-head"><div><span className="eyebrow">NOUVELLE PROPOSITION</span><h1>Ajouter un plugin</h1><p>Une soumission communautaire passe toujours par <strong>REVUE</strong>. Rien n'est publié directement.</p></div><span className="wizard-counter">{step<4?`${step+1}/4`:'✓'}</span></div>{step<4&&<div className="wizard-steps">{steps.map((s,i)=><div key={s} className={`wizard-step ${i===step?'current':''} ${i<step?'done':''}`}><span>{i<step?'✓':i+1}</span><b>{s}</b></div>)}</div>}
 {step===0&&<div className="wizard-panel"><div className="wizard-panel-title"><span>01</span><div><h2>Informations</h2><p>Présente ton plugin à la communauté.</p></div></div><div className="wizard-grid"><label>Nom du plugin<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex. NOVUS Essentials" maxLength={80}/></label><label>Version<input required value={form.version} onChange={e=>setForm({...form,version:e.target.value})} placeholder="1.4.2" maxLength={40}/></label><label>Auteur<input value={form.author||user.displayName} onChange={e=>setForm({...form,author:e.target.value})} placeholder={user.displayName}/></label><label>Catégorie<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>General</option><option>Gameplay</option><option>Administration</option><option>Economy</option><option>Utility</option><option>Protection</option><option>Cosmetics</option></select></label><label className="full">Description<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Fonctionnalités, dépendances, compatibilité Minecraft…" maxLength={1000}/></label><label className="full">Icône / logo <input value={form.icon} onChange={e=>setForm({...form,icon:e.target.value})} placeholder="URL facultative"/></label></div></div>}
 {step===1&&<div className="wizard-panel"><div className="wizard-panel-title"><span>02</span><div><h2>Fichier du plugin</h2><p>Dépose ton .jar ou .zip. Le fichier sera conservé en quarantaine.</p></div></div><input ref={inputRef} type="file" accept=".jar,.zip" hidden onChange={e=>acceptFile(e.target.files?.[0])}/><div className={`dropzone ${drag?'dragging':''} ${file?'has-file':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);acceptFile(e.dataTransfer.files?.[0])}} onClick={()=>inputRef.current?.click()}><div className="drop-icon">{file?'✓':'↑'}</div><h3>{file?file.name:'Glisse ton fichier ici'}</h3><p>{file?`${formatBytes(file.size)} · ${fileHash.slice(0,12)}…`:'ou clique pour sélectionner un .jar / .zip'}</p>{fileBusy&&<div className="wizard-progress"><i/></div>}</div>{file&&<div className="file-summary"><span>FICHIER SÉLECTIONNÉ</span><b>{file.name}</b><small>{formatBytes(file.size)} · SHA-256 <code>{fileHash}</code></small><button onClick={e=>{e.stopPropagation();setFile(null);setFileHash('')}}>Changer le fichier</button></div>}</div>}
 {step===2&&<div className="wizard-panel"><div className="wizard-panel-title"><span>03</span><div><h2>Vérification</h2><p>Nous préparons la soumission avant son passage en revue.</p></div></div><div className="checks">{[['Format','Extension .jar/.zip valide'],['Taille','Fichier sous la limite de 10 Mo'],['Intégrité','SHA-256 calculé côté navigateur'],['Métadonnées','Nom, version et description renseignés'],['Sécurité','Le fichier reste en quarantaine avant validation']].map(([name,detail],i)=>{const c=checks[i];return <div className={`check ${c?'passed':''}`} key={name}><span>{c?'✓':'○'}</span><div><b>{name}</b><small>{c?detail:'Vérification en cours…'}</small></div><i>{c?'OK':'…'}</i></div>})}</div>{checks.length<5&&<div className="analysis-line"><span/><b>Analyse en cours…</b></div>}</div>}
 {step===3&&<div className="wizard-panel"><div className="wizard-panel-title"><span>04</span><div><h2>Récapitulatif</h2><p>Vérifie les informations avant l'envoi définitif.</p></div></div><div className="submission-summary"><div className="summary-title"><div className="summary-icon">N</div><div><h3>{form.name}</h3><span>Version {form.version} · {form.category}</span></div><em>⏳ REVUE</em></div><p>{form.description}</p><dl><div><dt>Plugin</dt><dd>{file?.name}</dd></div><div><dt>Taille</dt><dd>{formatBytes(file?.size)}</dd></div><div><dt>SHA-256</dt><dd><code>{fileHash.slice(0,16)}…{fileHash.slice(-8)}</code></dd></div></dl></div><div className="quarantine-notice"><strong>🛡️ Votre plugin sera placé en quarantaine.</strong><span>Il ne sera pas publié immédiatement. Un membre autorisé devra examiner et valider votre soumission.</span></div></div>}
 {step===4&&submitted&&<div className="wizard-success"><div className="success-animation"><span>✓</span></div><span className="eyebrow">SOUMISSION TERMINÉE</span><h2>Ton plugin est maintenant en <em>REVUE.</em></h2><p>Il a été transmis à la quarantaine puis soumis au processus de validation NOVUS. Une publication n'est possible qu'après examen.</p><div className="pipeline"><span className="done">Upload</span><i>→</i><span className="done">Quarantaine</span><i>→</i><span className="done">Analyse</span><i>→</i><span className="current">Revue</span></div><div className="success-actions"><button className="primary" onClick={()=>setMode('contributions')}>Voir mes contributions</button><button onClick={()=>{resetWizard();setMode('plugins')}}>Retour aux plugins</button></div></div>}
 {step<4&&<div className="wizard-actions"><button disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))}>← Retour</button>{step===1?<button className="primary" disabled={!canNext} onClick={runChecks}>Vérifier le fichier →</button>:step===2?<button className="primary" disabled={!canNext} onClick={()=>setStep(3)}>Continuer →</button>:step===3?<button className="primary" disabled={!canNext||submitBusy} onClick={submitPlugin}>{submitBusy?'Envoi en cours…':'🚀 Envoyer en revue'}</button>:<button className="primary" disabled={!canNext} onClick={()=>setStep(step+1)}>Continuer →</button>}</div>}</section>}
 {mode==='contributions'&&user&&<section><div className="section-title"><span>MON HISTORIQUE</span><h1>Mes contributions</h1></div><div className="history-list">{contrib.map(c=><div key={c.id} className="history-item"><div><strong>{c.pluginName}</strong><small>{c.type==='edit'?'Modification':'Création'} · {new Date(c.createdAt).toLocaleString('fr-FR')}</small></div><b className={'state '+c.status}>{c.status}</b></div>)}{!contrib.length&&<div className="empty-community">Tu n'as encore aucune contribution.</div>}</div></section>}
 {mode==='account'&&user&&<section className="community-card"><span className="eyebrow">MON COMPTE</span><h1>Gérer mon profil</h1><label>Pseudo</label><input maxLength={40} value={profile.displayName} onChange={e=>setProfile({...profile,displayName:e.target.value})}/><label>Nouveau mot de passe</label><input minLength={12} type="password" placeholder="12 caractères minimum · laisser vide pour conserver" value={profile.password} onChange={e=>setProfile({...profile,password:e.target.value})}/><div className="account-meta"><span>Email <b>{user.email}</b></span><span>Rôle <b>{user.role}</b></span><span>Membre depuis <b>{new Date(user.createdAt).toLocaleDateString('fr-FR')}</b></span><span>Contributions <b>{user.contributions||0}</b></span></div><button className="primary" onClick={saveProfile}>Enregistrer</button></section>}
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="plugin-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span className="plugin-status">{selected.status.toUpperCase()}</span><h2>{selected.name}</h2><p>{selected.description}</p><div className="revision-note">Les modifications communautaires ne remplacent jamais directement la version publiée : elles créent une nouvelle révision qui retourne en test.</div>{user&&selected.status==='approved'&&<><input maxLength={40} value={selected.version||''} onChange={e=>setSelected({...selected,version:e.target.value})}/><textarea maxLength={1000} value={selected.description||''} onChange={e=>setSelected({...selected,description:e.target.value})}/><button className="primary" onClick={editPlugin}>Soumettre cette modification →</button></>}</div></div>}
 </main></div>;
}
