import React,{useEffect,useState} from 'react';
import './community.css';
const api=async(path,opts={})=>{const r=await fetch(path,{credentials:'same-origin',...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});const d=await r.json();if(!r.ok)throw Error(d.error||'Erreur');return d};
export default function Community(){const [user,setUser]=useState(null),[plugins,setPlugins]=useState([]),[q,setQ]=useState(''),[mode,setMode]=useState('plugins'),[busy,setBusy]=useState(true),[error,setError]=useState(''),[auth,setAuth]=useState({email:'',password:'',displayName:''}),[form,setForm]=useState({name:'',version:'',description:''}),[selected,setSelected]=useState(null),[contrib,setContrib]=useState([]),[profile,setProfile]=useState({displayName:'',password:''});
const load=async()=>{try{const m=await api('/api/me');setUser(m.user||null);const p=await api('/api/plugins');setPlugins(p.plugins||[]);if(m.user){const c=await api('/api/my/contributions');setContrib(c.contributions||[]);setProfile({displayName:m.user.displayName,password:''})}}catch(e){setError(e.message)}finally{setBusy(false)}};useEffect(()=>{load()},[]);
const search=async value=>{setQ(value);const d=await api('/api/plugins?q='+encodeURIComponent(value));setPlugins(d.plugins||[])};
const login=async register=>{setError('');try{const d=await api(register?'/api/auth/register':'/api/auth/login',{method:'POST',body:JSON.stringify(auth)});setUser(d.user);setMode('account');await load()}catch(e){setError(e.message)}};
const submitPlugin=async e=>{e.preventDefault();setError('');try{await api('/api/plugins',{method:'POST',body:JSON.stringify(form)});setForm({name:'',version:'',description:''});await load();setMode('contributions')}catch(e){setError(e.message)}};
const editPlugin=async()=>{if(!selected)return;try{await api('/api/plugins/'+selected.id,{method:'PATCH',body:JSON.stringify({name:selected.name,version:selected.version,description:selected.description})});setSelected(null);await load()}catch(e){setError(e.message)}};
const saveProfile=async()=>{try{const d=await api('/api/me',{method:'PATCH',body:JSON.stringify(profile)});setUser(d.user);setProfile({...profile,password:''});setError('Profil enregistré ✓')}catch(e){setError(e.message)}};
if(busy)return <div className="community"><div className="community-loading">NOVUS COMMUNITY · CHARGEMENT…</div></div>;
return <div className="community"><header className="community-nav"><a href="/" className="community-brand"><span>N</span>NOVUS</a><nav><button className={mode==='plugins'?'active':''} onClick={()=>setMode('plugins')}>Plugins</button><button className={mode==='contribute'?'active':''} onClick={()=>setMode('contribute')}>Contribuer</button>{user&&<button className={mode==='contributions'?'active':''} onClick={()=>setMode('contributions')}>Mes contributions</button>} {user&&<button className={mode==='account'?'active':''} onClick={()=>setMode('account')}>Mon compte</button>}</nav><div className="community-user">{user?<><span>{user.displayName}</span><button onClick={async()=>{await api('/api/auth/logout',{method:'POST'});setUser(null);setMode('plugins')}}>Déconnexion</button></>:<button onClick={()=>setMode('login')}>Se connecter</button>}</div></header><main className="community-main">{error&&<div className="community-alert">{error}<button onClick={()=>setError('')}>×</button></div>}
{mode==='login'&&!user&&<section className="community-card auth-card"><h1>Rejoindre NOVUS</h1><p>Crée ton compte pour publier, modifier et suivre tes contributions.</p><input placeholder="Email" type="email" value={auth.email} onChange={e=>setAuth({...auth,email:e.target.value})}/><input placeholder="Pseudo" value={auth.displayName} onChange={e=>setAuth({...auth,displayName:e.target.value})}/><input placeholder="Mot de passe · 12 caractères min." type="password" value={auth.password} onChange={e=>setAuth({...auth,password:e.target.value})}/><div className="auth-actions"><button className="primary" onClick={()=>login(true)}>Créer mon compte</button><button onClick={()=>login(false)}>Me connecter</button></div></section>}
{mode==='plugins'&&<><section className="community-hero"><div><span className="eyebrow">COMMUNITY PLUGIN HUB</span><h1>Les plugins de <em>la communauté.</em></h1><p>Explore, propose des améliorations et aide à faire évoluer NOVUS. Chaque modification communautaire repasse par une validation avant publication.</p></div><button className="primary" onClick={()=>user?setMode('contribute'):setMode('login')}>+ Proposer un plugin</button></section><div className="plugin-toolbar"><input value={q} onChange={e=>search(e.target.value)} placeholder="Rechercher un plugin…"/><span>{plugins.length} résultat{plugins.length>1?'s':''}</span></div><section className="plugin-grid">{plugins.map(p=><article className="community-plugin" key={p.id} onClick={()=>setSelected({...p})}><div className="plugin-status">{p.status==='approved'?'✓ VALIDÉ':p.status.toUpperCase()}</div><h2>{p.name}</h2><p>{p.description}</p><footer><span>v{p.version||'—'}</span><span>par {p.author}</span><span>{p.revisionCount} révision{p.revisionCount>1?'s':''}</span></footer></article>)}{!plugins.length&&<div className="empty-community">Aucun plugin ne correspond à ta recherche.</div>}</section></>}
{mode==='contribute'&&<section className="community-card"><span className="eyebrow">NOUVELLE PROPOSITION</span><h1>Ajouter un plugin</h1><p>Il sera automatiquement placé en <strong>REVUE</strong>. Rien n'est publié directement.</p>{user?<form onSubmit={submitPlugin}><input required placeholder="Nom du plugin" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Version" value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/><textarea required placeholder="Description, fonctionnalités, dépendances…" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button className="primary">Envoyer en revue →</button></form>:<button className="primary" onClick={()=>setMode('login')}>Créer un compte pour contribuer</button>}</section>}
{mode==='contributions'&&user&&<section><div className="section-title"><span>MON HISTORIQUE</span><h1>Mes contributions</h1></div><div className="history-list">{contrib.map(c=><div key={c.id} className="history-item"><div><strong>{c.pluginName}</strong><small>{c.type==='edit'?'Modification':'Création'} · {new Date(c.createdAt).toLocaleString('fr-FR')}</small></div><b className={'state '+c.status}>{c.status}</b></div>)}{!contrib.length&&<div className="empty-community">Tu n'as encore aucune contribution.</div>}</div></section>}
{mode==='account'&&user&&<section className="community-card"><span className="eyebrow">MON COMPTE</span><h1>Gérer mon profil</h1><label>Pseudo</label><input value={profile.displayName} onChange={e=>setProfile({...profile,displayName:e.target.value})}/><label>Nouveau mot de passe</label><input type="password" placeholder="Laisser vide pour conserver" value={profile.password} onChange={e=>setProfile({...profile,password:e.target.value})}/><div className="account-meta"><span>Rôle <b>{user.role}</b></span><span>Membre depuis <b>{new Date(user.createdAt).toLocaleDateString('fr-FR')}</b></span><span>Contributions <b>{user.contributions||0}</b></span></div><button className="primary" onClick={saveProfile}>Enregistrer</button></section>}
{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="plugin-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span className="plugin-status">{selected.status.toUpperCase()}</span><h2>{selected.name}</h2><input value={selected.version} onChange={e=>setSelected({...selected,version:e.target.value})}/><textarea value={selected.description} onChange={e=>setSelected({...selected,description:e.target.value})}/><p>Une modification envoyée par la communauté est toujours créée comme nouvelle révision et doit repasser en test avant d'être publiée.</p>{user&&<button className="primary" onClick={editPlugin}>Soumettre cette modification →</button>}</div></div>}
</main></div>}
